"base_path": "."
"base_url": "https://api.crowdin.com"  # optional (for Crowdin Enterprise only)
"preserve_hierarchy": false  # flatten tree on crowdin

"files" : [
  {
    "source" : "/locale/*.po",
    "translation" : "/locale/%locale_with_underscore%/LC_MESSAGES/%original_file_name%",
  }
]
