"base_path": "."
"base_url": "https://api.crowdin.com"  # optional (for Crowdin Enterprise only)
"preserve_hierarchy": false  # flatten tree on crowdin

"files" : [
  {
    "source" : "/locale/en/**/*.po",
    "translation" : "/locale/%two_letters_code%/LC_MESSAGES/%original_file_name%",
    "languages_mapping" : {
      "two_letters_code: " : {
        "de" : "de",
        "en" : "en",
        "en_GB": "en-GB",
        "en_US": "en-US",
        "es": "es-ES",
        "fr": "fr",
        "it": "it",
        "ru": "ru",
      }
    }
  }
]
